# Generated by Django 5.2.9 on 2025-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindScribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='services',
            field=models.CharField(default='', max_length=50),
        ),
    ]
