# Generated by Django 5.2.9 on 2025-12-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindScribe', '0003_alter_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ipv_4_local',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ipv_6',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, unique=True),
        ),
    ]
