# Generated by Django 5.2.9 on 2025-12-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WindScribe', '0004_alter_service_ipv_4_local_alter_service_ipv_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subscription',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WindScribe.subscription'),
        ),
    ]
